### ISSUE TITLE
artisan container cannot start

### ISSUE THREAD

**Issue by medfrk** [AdrienPoupa/laradose#1]
Hello, I find your docker configuration very interisting but something not work for me very will. When i launch docker-compose up the below error message apair I dont know how to fix it thank your very much and good luck :

ERROR: for laradose_artisan_1  Cannot start service artisan: OCI runtime create failed: container_linux.go:349: starting container process caused "exec: \"/var/www/artisan\": stat /var/www/artisan: no such file or directory": unknown

ERROR: for artisan  Cannot start service artisan: OCI runtime create failed: container_linux.go:349: starting container process caused "exec: \"/var/www/artisan\": stat /var/www/artisan: no such file or directory": unknown
ERROR: Encountered errors while bringing up the project.

**Comment by AdrienPoupa** [comment]
Hello,

What is your OS?

Are the Laradose files at the root of your project? (docker-compose.yml and the docker folder at the same level as your app folder, your .env file, etc)

**Comment by medfrk** [comment]
I use Mac OS catalina with docker last version, my project and docker folder are in the same level.

**Comment by AdrienPoupa** [comment]
I could not test on a Mac since I do not use it. It is weird though if you are in the same folder (docker-compose.yml and the artisan file side by side).

You could try to replace

```
entrypoint: ['/var/www/artisan']
```

with

```
entrypoint: ['php', '/var/www/artisan']
```

in docker-compose/yml to see if this changes things. If not, I do not know where the issue could be coming from.

Also, when you say: "my project and docker folder are in the same level" you mean that the docker folder is within your project, right? This is what it should look like:

![image](https://user-images.githubusercontent.com/15086425/86367237-b09dfd80-bc49-11ea-8e9b-fd8a6b8663ac.png)

**Comment by medfrk** [comment]
Thank's adrian it works now when adding this conf: entrypoint: ['php', '/var/www/artisan'].
Goo luck.

**Comment by AdrienPoupa** [comment]
Alright I will change the script then! Thanks for the report :)
