### ISSUE TITLE
Missing container for Laravel Scheduler

### ISSUE THREAD

**Issue by oanhnn** [AdrienPoupa/laradose#8]
I think we need a container for Laravel Scheduler. It can run with `/usr/sbin/crond -f -d 8` or shell script:
```
#!/bin/sh
set -e

cd /app
while [ true ]
do
  su-exec ${USER_ID:-82} php /var/www/artisan schedule:run --verbose --no-interaction &
  sleep 60
done
```

**Comment by AdrienPoupa** [comment]
Since this was not primarily intended for production this was not included, but it could be a good idea as an optional container.

I think we only need to create a copy of the artisan container and make it run `php artisan schedule:run` https://laravel.com/docs/7.x/scheduling#introduction

I will look into it.
